BusinessAdvanceManagement.UI/Controllers/AdvanceRequestController.cs
using BusinessAdvanceManagement.Business.Validation.AdvanceRequest;
using BusinessAdvanceManagement.Core;
using BusinessAdvanceManagement.Core.APIService;
using BusinessAdvanceManagement.Domain.DTOs.AdvanceRequest;
using BusinessAdvanceManagement.Domain.ViewModel.AdvanceRequest;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace BusinessAdvanceManagement.UI.Controllers
{
    public class AdvanceRequestController : BaseController
    {
        private readonly RequestDetailApiService _requestDetailApiService;
        private readonly AdvanceRequestApiService _api;
        private readonly GeneralApiService _generalapi;
        public AdvanceRequestController(AdvanceRequestApiService api, GeneralApiService generalapi, RequestDetailApiService requestDetailApiService)
        {
            _api = api;
            _generalapi = generalapi;
            _requestDetailApiService = requestDetailApiService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            var viewModel = new AdvanceRequestVM() { ProjectList=_generalapi.GetAllProject().Result.Datas.Select(p=>new SelectListItem() {  Text=p.ProjectName,Value=p.ProjectID.ToString()}).ToList()};
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add( AdvanceRequestVM aadvanceRequestAddDTO)
        {
            var validator = new AdvanceRequestValidator();
            var validationResult = validator.Validate(aadvanceRequestAddDTO);

            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }

                return View(new AdvanceRequestVM() { ProjectList = _generalapi.GetAllProject().Result.Datas.Select(p => new SelectListItem() { Text = p.ProjectName, Value = p.ProjectID.ToString() }).ToList()});
            }


            aadvanceRequestAddDTO.AdvanceRequestAddDTO.NextStatu = new AdvanceRequestHelper().NextStatuHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
            aadvanceRequestAddDTO.AdvanceRequestAddDTO.WorkerID = int.Parse(HttpContext.Session.GetString("ID"));
            aadvanceRequestAddDTO.AdvanceRequestAddDTO.NextStageUser = int.Parse(HttpContext.Session.GetString("WorkerManagerID"));
            aadvanceRequestAddDTO.AdvanceRequestAddDTO.AdvanceRequestStatus=new AdvanceRequestHelper().NextStatuHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
            var result =   await _api.Add(aadvanceRequestAddDTO.AdvanceRequestAddDTO);
            if (result.Datas==null)
            {
                return BadRequest(result.Message);
            }
            return RedirectToAction("Index","Home");
        }

        [HttpGet]
        public async Task<IActionResult> GetByWorker()
        {
            
            var result = await _api.GetByWorker(int.Parse(HttpContext.Session.GetString("ID")));
            if (result.Datas==null)
            {
                return RedirectToAction("Index","Home");
            }
            return View(result.Datas);
        }

        [HttpGet]
        public async Task<IActionResult> GetAdvanceList()
        {

            var result = await _api.GetByApproving(14);
            if (result.Datas == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(result.Datas);
        }
    }
}

BusinessAdvanceManagement.UI/Controllers/AdvanceRequestDetailController.cs
using BusinessAdvanceManagement.Core.APIService;
using BusinessAdvanceManagement.Domain.ViewModel.AdvanceRequestDetail;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusinessAdvanceManagement.UI.Controllers
{
    public class AdvanceRequestDetailController : BaseController
    {
        private readonly AdvanceRequestDetailApiService _api;
        private readonly AdvanceRequestApiService _requestApi;

        public AdvanceRequestDetailController(AdvanceRequestDetailApiService api, AdvanceRequestApiService requestApi)
        {
            _api = api;
            _requestApi = requestApi;
        }

        [HttpGet]
        public IActionResult GetByRequest(int advanceRequestID)
        {
            var viewModel = new AdvanceRequestDetailListPageVM()
            { 
                AdvanceRequestDetailListDTO = _api.GetByRequest(advanceRequestID).Result.Datas,
                AdvanceRequestListDTO = _requestApi.GetByWorker(int.Parse(HttpContext.Session.GetString("ID"))).Result.Datas.Where(r => r.AdvanceRequestID == advanceRequestID).FirstOrDefault()
            };
            
            return View(viewModel);
        }
    }
}

BusinessAdvanceManagement.UI/Controllers/RequestDetailController.cs
using BusinessAdvanceManagement.Business.Validation.RequestDetail;
using BusinessAdvanceManagement.Core;
using BusinessAdvanceManagement.Core.APIService;
using BusinessAdvanceManagement.Domain.DTOs.RequestDetail;
using BusinessAdvanceManagement.Domain.ViewModel.AdvanceRequestDetail;
using BusinessAdvanceManagement.Domain.ViewModel.RequestDetail;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusinessAdvanceManagement.UI.Controllers
{
    public class RequestDetailController : BaseController
    {
        RequestDetailApiService _api;
        private readonly AdvanceRequestDetailApiService _requestDetailApi;
        private readonly AdvanceRequestApiService _requestApi;
        private readonly GeneralApiService _generalApi;

        public RequestDetailController(RequestDetailApiService api, AdvanceRequestDetailApiService requestDetailApi, AdvanceRequestApiService requestApi, GeneralApiService generalApi)
        {
            _api = api;
            _requestApi = requestApi;
            _requestDetailApi = requestDetailApi;
            _generalApi = generalApi;
        }

        [HttpGet]
        public IActionResult PendingApproval()
        {
            var data = _api.GetAdvanceRequest(new AdvanceRequestHelper().StatuFilterQueryHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")))).Result;
            if (data.Datas==null)
            {
                return RedirectToAction("Index","Home");
            }
            var viewModel = new PendingApprovalPageVM()
            {
                RolID = int.Parse(HttpContext.Session.GetString("WorkerRolID")),
                ConfirmAdvanceListDTOs = data.Datas
            };
            
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult PendingApprovalDetail(int advanceRequestID)
        {
            
            var viewModel = new PendingApprovalDetailPageVM()
            {
                RoleID= int.Parse(HttpContext.Session.GetString("WorkerRolID")),
                OnlyAdvanceRequestListDTO = _requestApi.GetByRequestID(advanceRequestID).Result.Datas.FirstOrDefault(),
                AdvanceRequestDetailListDTO= _requestDetailApi.GetByRequest(advanceRequestID).Result.Datas
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult PendingApprovalDetail(PendingApprovalDetailPageVM rrequestDetailAddDTO, string operation)
        {
            var validator = new RequestDetailValidator();
            var validationResult = validator.Validate(rrequestDetailAddDTO);
            

            if (operation=="add")
            {
                var parametre1 = new AdvanceRequestHelper().RequestDetailAddNextStageUserHelper(_generalApi.GetByRoleIDRule(int.Parse(HttpContext.Session.GetString("WorkerRolID"))).Result.Datas.FirstOrDefault(), _requestApi.GetByRequestID(rrequestDetailAddDTO.RequestDetailAddDTO.AdvanceRequestID).Result.Datas.FirstOrDefault().Amount, int.Parse(HttpContext.Session.GetString("WorkerRolID")));

                if (parametre1 == 1)
                {
                    rrequestDetailAddDTO.RequestDetailAddDTO.NextStageUser = 6;
                    rrequestDetailAddDTO.RequestDetailAddDTO.NextStatu = 10;
                    rrequestDetailAddDTO.RequestDetailAddDTO.ApprovingDisapproving = int.Parse(HttpContext.Session.GetString("ID"));
                    rrequestDetailAddDTO.RequestDetailAddDTO.ApprovingDisapprovingRole = int.Parse(HttpContext.Session.GetString("WorkerRolID"));
                    rrequestDetailAddDTO.RequestDetailAddDTO.RequestStatuID = new AdvanceRequestHelper().NextStatuHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
                }
                if (parametre1==2)
                {
                    rrequestDetailAddDTO.RequestDetailAddDTO.NextStageUser = int.Parse(HttpContext.Session.GetString("WorkerManagerID"));
                    rrequestDetailAddDTO.RequestDetailAddDTO.NextStatu = new AdvanceRequestHelper().NextStatuHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
                    rrequestDetailAddDTO.RequestDetailAddDTO.RequestStatuID = new AdvanceRequestHelper().NextStatuHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
                }
                if (parametre1==3)
                {
                    //onay sınırları içerisinde, finans müdürüne ata
                    rrequestDetailAddDTO.RequestDetailAddDTO.NextStageUser = 6;
                    rrequestDetailAddDTO.RequestDetailAddDTO.NextStatu = 10;
                    rrequestDetailAddDTO.RequestDetailAddDTO.ApprovingDisapproving= int.Parse(HttpContext.Session.GetString("ID"));
                    rrequestDetailAddDTO.RequestDetailAddDTO.ApprovingDisapprovingRole= int.Parse(HttpContext.Session.GetString("WorkerRolID"));
                    rrequestDetailAddDTO.RequestDetailAddDTO.RequestStatuID = 10;
                }

                

                if (!validationResult.IsValid)
                {
                    foreach (var error in validationResult.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }

                    return View(new PendingApprovalDetailPageVM()
                    {
                        RoleID = int.Parse(HttpContext.Session.GetString("WorkerRolID")),
                        OnlyAdvanceRequestListDTO = _requestApi.GetByRequestID(rrequestDetailAddDTO.RequestDetailAddDTO.AdvanceRequestID).Result.Datas.FirstOrDefault(),
                        AdvanceRequestDetailListDTO = _requestDetailApi.GetByRequest(rrequestDetailAddDTO.RequestDetailAddDTO.AdvanceRequestID).Result.Datas
                    });
                }

                rrequestDetailAddDTO.RequestDetailAddDTO.StatuID = new AdvanceRequestHelper().RequestDetailAddStatuHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
                rrequestDetailAddDTO.RequestDetailAddDTO.CreatedDate = DateTime.Now;
                rrequestDetailAddDTO.RequestDetailAddDTO.TransactionOwner = int.Parse(HttpContext.Session.GetString("ID"));
               
                var result = _api.Add(rrequestDetailAddDTO.RequestDetailAddDTO);
            }
            if (operation=="red")
            {
                rrequestDetailAddDTO.RequestDetailAddDTO.ConfirmAmount = 0;
                rrequestDetailAddDTO.RequestDetailAddDTO.StatuID = 13;
                rrequestDetailAddDTO.RequestDetailAddDTO.ApprovingDisapproving = int.Parse(HttpContext.Session.GetString("ID"));
                rrequestDetailAddDTO.RequestDetailAddDTO.ApprovingDisapprovingRole = int.Parse(HttpContext.Session.GetString("WorkerRolID"));
                
                var result = _api.Red(rrequestDetailAddDTO.RequestDetailAddDTO);
            }
            if (operation=="insert")
            {
                //fm
                rrequestDetailAddDTO.RequestDetailAddDTO.StatuID = new AdvanceRequestHelper().RequestDetailAddStatuHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
                rrequestDetailAddDTO.RequestDetailAddDTO.CreatedDate = DateTime.Now;
                rrequestDetailAddDTO.RequestDetailAddDTO.TransactionOwner = int.Parse(HttpContext.Session.GetString("ID"));
                rrequestDetailAddDTO.RequestDetailAddDTO.RequestStatuID = 14;
                rrequestDetailAddDTO.RequestDetailAddDTO.NextStageUser = 8;
                rrequestDetailAddDTO.RequestDetailAddDTO.NextStatu = new AdvanceRequestHelper().NextStatuHelper(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
                
                if (!validationResult.IsValid)
                {
                    foreach (var error in validationResult.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }

                    return View(new PendingApprovalDetailPageVM()
                    {
                        RoleID = int.Parse(HttpContext.Session.GetString("WorkerRolID")),
                        OnlyAdvanceRequestListDTO = _requestApi.GetByRequestID(rrequestDetailAddDTO.RequestDetailAddDTO.AdvanceRequestID).Result.Datas.FirstOrDefault(),
                        AdvanceRequestDetailListDTO = _requestDetailApi.GetByRequest(rrequestDetailAddDTO.RequestDetailAddDTO.AdvanceRequestID).Result.Datas
                    });
                }

                var result = _api.Add(rrequestDetailAddDTO.RequestDetailAddDTO);
            }
            if (operation=="makbuz")
            {
                
                if (!validationResult.IsValid)
                {
                    foreach (var error in validationResult.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }

                    return View(new PendingApprovalDetailPageVM()
                    {
                        RoleID = int.Parse(HttpContext.Session.GetString("WorkerRolID")),
                        OnlyAdvanceRequestListDTO = _requestApi.GetByRequestID(rrequestDetailAddDTO.RequestDetailAddDTO.AdvanceRequestID).Result.Datas.FirstOrDefault(),
                        AdvanceRequestDetailListDTO = _requestDetailApi.GetByRequest(rrequestDetailAddDTO.RequestDetailAddDTO.AdvanceRequestID).Result.Datas
                    });
                }
            }
           
            return RedirectToAction("Index","Home");
        }
    }
}

BusinessAdvanceManagement.UI/Views/AdvanceRequest/Add.cshtml
@model BusinessAdvanceManagement.Domain.ViewModel.AdvanceRequest.AdvanceRequestVM
@{
    ViewData["Title"] = "Add";
}

<link href="~/css/AdvanceRequest/addpage.css" rel="stylesheet" />
<div class="container-fluid wrapper">
    <h1>Yeni Avans Oluşturma Ekranı</h1>
    <form asp-controller="AdvanceRequest" asp-action="Add"  method="post">
        <div class="input-group">
            <label>Avans Miktarı:</label>
            <input asp-for="@Model.AdvanceRequestAddDTO.Amount"  type="text" placeholder="TL" />
            <span asp-validation-for="@Model.AdvanceRequestAddDTO.Amount"></span>
        </div>
        <div class="input-group">
            <label>İstenilen Tarih:</label>
            <input asp-for="@Model.AdvanceRequestAddDTO.DesiredDate" type="datetime-local" >
            <span asp-validation-for="@Model.AdvanceRequestAddDTO.DesiredDate"></span>
        </div>
        <div class="input-group">
            <label style="display:block">Projeler</label>
            
            <select asp-items="@Model.ProjectList" asp-for="@Model.AdvanceRequestAddDTO.ProjectID">
            </select>
            <span asp-validation-for="@Model.AdvanceRequestAddDTO.ProjectID"></span>
        </div>
        <div class="input-group">
            <label>Açıklama:</label>
            <input asp-for="@Model.AdvanceRequestAddDTO.Description" type="text" placeholder="Açıklama giriniz." />
        </div>
        <span asp-validation-for="@Model.AdvanceRequestAddDTO.Description"></span>
        <div class="input-group">
            <button class="btn btn-success">KAYDET</button>
        </div>
    </form>

</div>

BusinessAdvanceManagement.UI/Views/AdvanceRequest/GetAdvanceList.cshtml
@model IEnumerable<BusinessAdvanceManagement.Domain.DTOs.AdvanceRequest.AdvanceRequestListsDTO>
@{
    ViewData["Title"] = "GetAdvanceList";
}

<h1>Avans Listeleri</h1>

<div class="table-responsive table-container">
    <table class="table table-bordered border-dark">
       
        
            <thead>
                <tr>
                    <th>Çalışanın Adı:</th>
                    <th>Unvanı</th>
                    <th>Birimi</th>
                    <th>Talep Tutarı</th>
                    <th>Talep Oluşturma Tarihi</th>
                    <th>İstenilen Tarih</th>
                    <th>Proje</th>
                    <th>Talep Durumu</th>
                    <th>Onaylayan/Reddeden</th>
                    <th>Onaylayan/Reddeden unvan</th>
                    <th>Onay/Red tarihi</th>
                    <th>Onaylanan Tutar</th>
                    <th>Belirlenen Ödeme Tarihi</th>
                    <th>Ödeme Yapılan Tarih</th>
                    <th>Geri Ödeme durumu</th>
                    <th>Detay</th>
                </tr>
            </thead>
            <tbody>
                
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.WorkerName @item.WorkerSurname</td>
                        <td>@item.RoleName</td>
                        <td>@item.UnitName</td>
                        <td>@item.Amount</td>
                        <td>@item.CreatedDate</td>
                        <td>@item.DesiredDate</td>
                        <td>@item.ProjectName</td>
                        <td>@item.StatuName</td>
                        <td>@item.AppWorkerName @item.AppWorkerSurname</td>
                        <td>@item.AppRoleName</td>
                        <td>@item.ApprovalRejectionDate</td>
                        <td>@item.ConfirmedAmount</td>
                        <td>@item.DeterminedPaymentDate</td>
                        <td>@item.PaymentMadeDate</td>
                        <td>@item.StatusName</td>
                        
                        <td>
                            <a asp-controller="RequestDetail" asp-action="PendingApprovalDetail" asp-route-advanceRequestID="@item.AdvanceRequestID" class="btn btn-link">
                                <i class="far fa-hand-point-right"></i>
                            </a>
                        </td>
                    </tr>
                }
                    


                

            </tbody>
        
    </table>
</div>

BusinessAdvanceManagement.UI/Views/AdvanceRequest/GetByWorker.cshtml
@model IEnumerable<BusinessAdvanceManagement.Domain.DTOs.AdvanceRequest.AdvanceRequestListDTO>
    <style>
        .table-container {
            overflow-x: auto;
        }
    </style>
<div class="container-fluid">
    <h1>Geçmiş Avans Taleplerim</h1>
    <div class="table-responsive table-container">

        <table class="table table-striped table-bordered border-dark">
            <thead>
                <tr>
                    <th>Talep Tutarı</th>
                    <th>Talep Oluşturulma Tarihi</th>
                    <th>İstenilen Tarihi</th>
                    <th>Proje</th>
                    <th>Talep Durumu</th>
                    <th>Onaylayan/Reddeden</th>
                    <th>Onaylayan/Reddeden Unvan</th>
                    <th>Onay/Red Tarihi</th>
                    <th>Onaylanan Tutar</th>
                    <th>Belirlenen Ödeme Tarihi</th>
                    <th>Odeme Yapılan tarih</th>
                    <th>Geri Ödeme Durumu</th>
                    <th>Detay</th>
                </tr>

            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Amount</td>
                        <td>@item.CreatedDate</td>
                        <td>@item.DesiredDate</td>
                        <td>@item.ProjectName</td>
                        <td>@item.StatuName</td>
                        <td>@item.WorkerName @item.WorkerSurname</td>
                        <td>@item.RoleName</td>
                        <td>
                            @if (item.ApprovalRejectionDate != DateTime.MinValue)
                            {
                                @item.ApprovalRejectionDate
                            }

                        </td>
                        <td>
                            @if (item.ConfirmedAmount != 0)
                            {
                                @item.ConfirmedAmount
                            }
                        </td>
                        <td>
                            @if (item.DeterminedPaymentDate != DateTime.MinValue)
                            {
                                @item.DeterminedPaymentDate
                            }
                        </td>
                        <td>
                            @if (item.PaymentMadeDate != DateTime.MinValue)
                            {
                                @item.PaymentMadeDate
                            }
                        </td>
                        <td>@item.StatusName</td>
                        <td>
                            <a asp-controller="AdvanceRequestDetail" asp-action="GetByRequest" asp-route-advanceRequestID="@item.AdvanceRequestID" class="btn btn-link">
                                <i class="far fa-hand-point-right"></i>
                            </a>
                        </td>

                    </tr>
                }

            </tbody>

        </table>
    </div>


</div>