BusinessAdvanceManagement.UI/ViewComponents/PageRoleViewComponent.cs
using BusinessAdvanceManagement.Core.APIService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusinessAdvanceManagement.UI.ViewComponents
{
    public class PageRoleViewComponent : ViewComponent
    {
        private readonly GeneralApiService _generalApiService;

        public PageRoleViewComponent(GeneralApiService generalApiService)
        {
            _generalApiService = generalApiService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await  _generalApiService.GetByIDRolePage(int.Parse(HttpContext.Session.GetString("WorkerRolID")));
            return View(result.Datas);
        }
    }
}

BusinessAdvanceManagement.UI/ViewComponents/WorkerInformationViewComponent.cs
using BusinessAdvanceManagement.Domain.ViewModel.Worker;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusinessAdvanceManagement.UI.ViewComponents
{
    public class WorkerInformationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var viewModel = new WorkerLabelVM() {WorkerName= HttpContext.Session.GetString("WorkerName"),WorkerSurname= HttpContext.Session.GetString("WorkerSurname"), RoleName= HttpContext.Session.GetString("WorkerRoleName") };
            
            return View(viewModel);
        }
    }
}

BusinessAdvanceManagement.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="styles.css" />
    <link href="~/css/Dashboard/styles.css" rel="stylesheet" />
    <title>İş Avansı Yönetim Sistemi</title>
</head>

<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom">
                <i class="fas fa-user-secret me-2"></i>İş Avans Yönetimi
            </div>
            <div class="list-group list-group-flush my-3">

               
                @await Component.InvokeAsync("PageRole")
                <a asp-controller="Auth" asp-action="Logout" class="list-group-item list-group-item-action bg-transparent text-danger fw-bold">
                    <i class="fas fa-power-off me-2"></i>Logout
                </a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
                <div class="d-flex align-items-center">
                    <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                    <h2 class="fs-2 m-0">Dashboard</h2>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle second-text fw-bold" href="#" id="navbarDropdown"
                               role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user me-2"></i>@await Component.InvokeAsync("WorkerInformation")
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                                <li><a class="dropdown-item" href="#">Settings</a></li>
                                <li><a class="dropdown-item" href="#">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid px-4">
               
                <main>
                    <div class="row">
                        @RenderBody()
                    </div>
                </main>
                

            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>
</body>

</html>

BusinessAdvanceManagement.UI/Views/Shared/_sidebarpartial.cshtml
@model IEnumerable<BusinessAdvanceManagement.Domain.DTOs.PageRole.PageRoleListDTO>
    <link href="~/css/Dashboard/styles.css" rel="stylesheet" />
@foreach (var item in Model)
{
    <a asp-controller="@item.PageController"  asp-action="@item.PageAction" class="list-group-item list-group-item-action bg-transparent second-text active">
        <i class="fas fa-tachometer-alt me-2"></i>@item.PageName
    </a>
}